"""create embeddings table

Revision ID: 166cad5ebad8
Revises: 81d3346e0e69
Create Date: 2026-07-09 12:13:01.560712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '166cad5ebad8'
down_revision: Union[str, Sequence[str], None] = '81d3346e0e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model_id', sa.UUID(), nullable=False),
    sa.Column('embedding_job_id', sa.UUID(), nullable=False),
    sa.Column('vector', Vector(1536), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['embedding_job_id'], ['embedding_jobs.id'], ),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_embeddings_document_id'), 'embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_embeddings_embedding_job_id'), 'embeddings', ['embedding_job_id'], unique=False)
    op.create_index(op.f('ix_embeddings_embedding_model_id'), 'embeddings', ['embedding_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_embedding_model_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_embedding_job_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_document_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
