"""create embedding provider and model tables

Revision ID: 53dc9c2c1c25
Revises: 0a67fe7a3d46
Create Date: 2026-07-09 09:18:55.830379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dc9c2c1c25'
down_revision: Union[str, Sequence[str], None] = '0a67fe7a3d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
