"""create embedding jobs table

Revision ID: 81d3346e0e69
Revises: 9eb743a69bd5
Create Date: 2026-07-09 10:11:07.165672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d3346e0e69'
down_revision: Union[str, Sequence[str], None] = '9eb743a69bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_jobs_chunk_id'), 'embedding_jobs', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_document_id'), 'embedding_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_embedding_model_id'), 'embedding_jobs', ['embedding_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_jobs_embedding_model_id'), table_name='embedding_jobs')
    op.drop_index(op.f('ix_embedding_jobs_document_id'), table_name='embedding_jobs')
    op.drop_index(op.f('ix_embedding_jobs_chunk_id'), table_name='embedding_jobs')
    op.drop_table('embedding_jobs')
    # ### end Alembic commands ###
