"""create embedding provider and model tables

Revision ID: 9eb743a69bd5
Revises: 53dc9c2c1c25
Create Date: 2026-07-09 09:34:33.114089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb743a69bd5'
down_revision: Union[str, Sequence[str], None] = '53dc9c2c1c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_providers_provider_code'), 'embedding_providers', ['provider_code'], unique=True)
    op.create_table('embedding_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('distance_metric', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['embedding_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_models_model_name'), 'embedding_models', ['model_name'], unique=False)
    op.create_index(op.f('ix_embedding_models_provider_id'), 'embedding_models', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_models_provider_id'), table_name='embedding_models')
    op.drop_index(op.f('ix_embedding_models_model_name'), table_name='embedding_models')
    op.drop_table('embedding_models')
    op.drop_index(op.f('ix_embedding_providers_provider_code'), table_name='embedding_providers')
    op.drop_table('embedding_providers')
    # ### end Alembic commands ###
