import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Badge } from "../components/ui/Badge";
import { ApiClientError } from "../lib/api";
import { useAuth } from "../modules/auth/AuthContext";
import { createBrand, deleteBrand, fetchBrands, updateBrand } from "../modules/brands/api";
import type { Brand, BrandInput } from "../modules/brands/types";
import { createCategoryPolicy, deleteCategoryPolicy, fetchCategoryPolicies, fetchProductCategories, updateCategoryPolicy } from "../modules/product-categories/api";
import type { CategoryPolicy, CategoryPolicyInput, ProductCategory } from "../modules/product-categories/types";
import { label } from "../modules/product-research/format";

const empty:BrandInput={brand_code:"",brand_name:"",luxury_tier:"luxury",official_site_url:null,online_purchase_policy:"unknown",purchase_restriction_notes:null,is_research_enabled:true,is_active:true};
const emptyPolicy:CategoryPolicyInput={category_id:"",online_purchase_policy:"unknown",research_enabled:true,policy_notes:null,checked_at:null};

export function BrandsPage(){
 const {user}=useAuth(); const admin=user?.role==="admin"; const[data,setData]=useState<Brand[]>([]); const[loading,setLoading]=useState(true); const[error,setError]=useState(""); const[editing,setEditing]=useState<Brand|null|undefined>(); const[policyBrand,setPolicyBrand]=useState<Brand|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{setData((await fetchBrands({page_size:100,is_active:undefined})).items);setError("");}catch(e){setError(e instanceof Error?e.message:"Failed to load brands.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const remove=async(b:Brand)=>{if(!window.confirm(`Delete ${b.brand_name}?`))return;try{await deleteBrand(b.id);await load();}catch(e){setError(e instanceof ApiClientError&&e.code==="BRAND_IN_USE"?"This brand is in use. Deactivate it instead.":e instanceof Error?e.message:"Delete failed.");}};
 return <section className="page-section"><div className="page-section__header"><div><h1>Brands</h1><p>Global luxury brand master and category purchase policies.</p></div>{admin&&<button className="primary-button" onClick={()=>setEditing(null)}>Add Brand</button>}</div>{error&&<div className="form-error-banner">{error}</div>}{loading?<div className="page-status">Loading brands...</div>:!data.length?<div className="panel panel--empty"><h2>No brands found.</h2><p>No brands match the current filters.</p></div>:<div className="panel"><div className="table-wrapper"><table className="data-table"><thead><tr><th>Brand</th><th>Tier</th><th>Default policy</th><th>Research</th><th>Active</th><th>Actions</th></tr></thead><tbody>{data.map(b=><tr key={b.id}><td><strong>{b.brand_name}</strong><div className="subtle">{b.brand_code}</div></td><td><Badge>{label(b.luxury_tier)}</Badge></td><td><Badge tone={b.online_purchase_policy==="research_only"?"warning":"neutral"}>{label(b.online_purchase_policy)}</Badge></td><td>{b.is_research_enabled?"Enabled":"Disabled"}</td><td>{b.is_active?"Active":"Inactive"}</td><td><div className="row-actions"><button className="secondary-button" onClick={()=>setPolicyBrand(b)}>Category Policies</button>{admin&&<><button className="secondary-button" onClick={()=>setEditing(b)}>Edit</button><button className="secondary-button" onClick={()=>void remove(b)}>Delete</button></>}</div></td></tr>)}</tbody></table></div></div>}{editing!==undefined&&<BrandForm brand={editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);void load();}}/>}{policyBrand&&<PolicyPanel brand={policyBrand} admin={admin} onClose={()=>setPolicyBrand(null)}/>}</section>;
}

function BrandForm({brand,onClose,onSaved}:{brand:Brand|null;onClose:()=>void;onSaved:()=>void}){const[form,setForm]=useState<BrandInput>(brand?{brand_code:brand.brand_code,brand_name:brand.brand_name,luxury_tier:brand.luxury_tier,official_site_url:brand.official_site_url,online_purchase_policy:brand.online_purchase_policy,purchase_restriction_notes:brand.purchase_restriction_notes,is_research_enabled:brand.is_research_enabled,is_active:brand.is_active}:empty);const[error,setError]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();try{brand?await updateBrand(brand.id,form):await createBrand(form);onSaved();}catch(x){setError(x instanceof Error?x.message:"Save failed.");}};return <div className="modal-backdrop"><form className="modal-panel research-form" aria-label="Brand form" onSubmit={e=>void submit(e)}><div className="modal-panel__header"><h2>{brand?"Edit Brand":"Add Brand"}</h2><button type="button" className="secondary-button" onClick={onClose}>Close</button></div>{error&&<div className="form-error-banner">{error}</div>}<Field name="Brand code" value={form.brand_code} disabled={!!brand} set={v=>setForm({...form,brand_code:v})}/><Field name="Brand name" value={form.brand_name} set={v=>setForm({...form,brand_name:v})}/><label className="form-field">Luxury tier<select className="form-field__input" value={form.luxury_tier} onChange={e=>setForm({...form,luxury_tier:e.target.value as BrandInput["luxury_tier"]})}>{["ultra_luxury","luxury","premium"].map(x=><option key={x}>{x}</option>)}</select></label><label className="form-field">Purchase policy<select className="form-field__input" value={form.online_purchase_policy} onChange={e=>setForm({...form,online_purchase_policy:e.target.value as BrandInput["online_purchase_policy"]})}>{["normal","limited","category_limited","boutique_only","research_only","unknown"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><Field name="Official site URL" value={form.official_site_url||""} set={v=>setForm({...form,official_site_url:v||null})}/><Field name="Restriction notes" value={form.purchase_restriction_notes||""} set={v=>setForm({...form,purchase_restriction_notes:v||null})}/><label className="checkbox-field"><input type="checkbox" checked={form.is_research_enabled} onChange={e=>setForm({...form,is_research_enabled:e.target.checked})}/>Research enabled</label><label className="checkbox-field"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Active</label><button className="primary-button">Save Brand</button></form></div>}

function PolicyPanel({brand,admin,onClose}:{brand:Brand;admin:boolean;onClose:()=>void}){const[items,setItems]=useState<CategoryPolicy[]>([]);const[categories,setCategories]=useState<ProductCategory[]>([]);const[editing,setEditing]=useState<CategoryPolicy|null|undefined>();const[error,setError]=useState("");const load=useCallback(async()=>{try{const[p,c]=await Promise.all([fetchCategoryPolicies(brand.id),fetchProductCategories()]);setItems(p);setCategories(c);setError("");}catch(e){setError(e instanceof Error?e.message:"Load failed.");}},[brand.id]);useEffect(()=>{void load();},[load]);return <div className="modal-backdrop"><section className="modal-panel" aria-label="Category policies"><div className="modal-panel__header"><div><h2>{brand.brand_name} Category Policies</h2><p>Default brand policy: {label(brand.online_purchase_policy)}</p></div><button className="secondary-button" onClick={onClose}>Close</button></div>{error&&<div className="form-error-banner">{error}</div>}{admin&&<button className="primary-button" onClick={()=>setEditing(null)}>Add Policy</button>}<div className="table-wrapper"><table className="data-table"><thead><tr><th>Category</th><th>Policy</th><th>Research</th><th>Checked At</th><th>Notes</th>{admin&&<th>Actions</th>}</tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.category.category_name}</td><td>{label(x.online_purchase_policy)}</td><td>{x.research_enabled?"Enabled":"Disabled"}</td><td>{x.checked_at?new Date(x.checked_at).toLocaleDateString():"-"}</td><td>{x.policy_notes||"-"}</td>{admin&&<td><button className="secondary-button" onClick={()=>setEditing(x)}>Edit</button><button className="secondary-button" onClick={()=>void deleteCategoryPolicy(brand.id,x.id).then(load)}>Delete</button></td>}</tr>)}</tbody></table></div>{editing!==undefined&&<PolicyForm brand={brand} policy={editing} categories={categories} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);void load();}}/>}</section></div>}

function PolicyForm({brand,policy,categories,onClose,onSaved}:{brand:Brand;policy:CategoryPolicy|null;categories:ProductCategory[];onClose:()=>void;onSaved:()=>void}){const[form,setForm]=useState<CategoryPolicyInput>(policy?{category_id:policy.category_id,online_purchase_policy:policy.online_purchase_policy,research_enabled:policy.research_enabled,policy_notes:policy.policy_notes,checked_at:policy.checked_at}:emptyPolicy);const submit=async(e:FormEvent)=>{e.preventDefault();policy?await updateCategoryPolicy(brand.id,policy.id,form):await createCategoryPolicy(brand.id,form);onSaved();};return <form className="panel research-form" aria-label="Category policy form" onSubmit={e=>void submit(e)}><label className="form-field">Category<select disabled={!!policy} required className="form-field__input" value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Select...</option>{categories.map(x=><option key={x.id} value={x.id}>{x.category_name}</option>)}</select></label><label className="form-field">Policy<select className="form-field__input" value={form.online_purchase_policy} onChange={e=>setForm({...form,online_purchase_policy:e.target.value as CategoryPolicyInput["online_purchase_policy"]})}>{["normal","limited","category_limited","boutique_only","research_only","unknown"].map(x=><option key={x}>{x}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={form.research_enabled} onChange={e=>setForm({...form,research_enabled:e.target.checked})}/>Research enabled</label><Field name="Notes" value={form.policy_notes||""} set={v=>setForm({...form,policy_notes:v||null})}/><div className="row-actions"><button className="primary-button">Save Policy</button><button type="button" className="secondary-button" onClick={onClose}>Cancel</button></div></form>}
function Field({name,value,set,disabled=false}:{name:string;value:string;set:(v:string)=>void;disabled?:boolean}){return <label className="form-field">{name}<input disabled={disabled} className="form-field__input" value={value} onChange={e=>set(e.target.value)}/></label>}
