import { render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";
import { fetchBrands } from "../modules/brands/api";
import { fetchCandidates } from "../modules/product-research/api";
import { fetchSuppliers } from "../modules/suppliers/api";
import { ProductResearchPage } from "./ProductResearchPage";

vi.mock("../modules/brands/api",()=>({fetchBrands:vi.fn()}));vi.mock("../modules/suppliers/api",()=>({fetchSuppliers:vi.fn()}));vi.mock("../modules/product-research/api",()=>({fetchCandidates:vi.fn(),deleteCandidate:vi.fn()}));
const brand={id:"b",brand_code:"gucci",brand_name:"Gucci",luxury_tier:"luxury" as const,official_site_url:null,online_purchase_policy:"unknown" as const,purchase_restriction_notes:null,is_research_enabled:true,is_active:true,created_at:"",updated_at:""};
const supplier={id:"s",owner_user_id:"u",name:"EU Shop",country_code:"IT",website_url:"https://example.com",supplier_type:"boutique",default_currency:"EUR",ships_to_japan:true,vat_policy:"unknown",vat_rate:null,japan_shipping_cost:"0",buyma_allowed_status:"allowed",buyma_status_checked_at:null,research_status:"approved",notes:null,is_active:true,brands:[],created_at:"",updated_at:""};
describe("ProductResearchPage",()=>{it("renders positive and negative profit explicitly",async()=>{vi.mocked(fetchBrands).mockResolvedValue({items:[brand],page:1,page_size:100,total:1,total_pages:1});vi.mocked(fetchSuppliers).mockResolvedValue({items:[supplier],page:1,page_size:100,total:1,total_pages:1});const base={owner_user_id:"u",supplier_id:"s",brand_id:"b",supplier_product_url:"https://example.com/i",supplier_product_code:null,product_name:"Bag",category:null,supplier_price:"100",supplier_currency:"EUR",vat_policy:"unknown",vat_rate:null,export_price:null,japan_shipping_cost:"0",exchange_rate:"160",supplier_cost_jpy:"16000",estimated_import_cost:"0",estimated_other_cost:"0",total_cost:"16000",buyma_price:"20000",buyma_fee_rate:"0.05",buyma_fee:"1000",profit_rate:"0.15",availability_status:"in_stock",research_status:"profitable",checked_at:null,online_purchase_available:true,is_active:true,created_at:"",updated_at:""};vi.mocked(fetchCandidates).mockResolvedValue({items:[{...base,id:"1",profit_amount:"3000"},{...base,id:"2",product_name:"Loss Bag",profit_amount:"-2000",profit_rate:"-0.10"}],page:1,page_size:20,total:2,total_pages:1});render(<MemoryRouter><ProductResearchPage/></MemoryRouter>);await waitFor(()=>expect(screen.getAllByText("Gucci").length).toBeGreaterThan(0));expect(screen.getAllByText(/3,000/).length).toBeGreaterThan(0);expect(screen.getAllByText(/-.*2,000/).length).toBeGreaterThan(0);});});
