import { useCallback,useEffect,useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Badge } from "../components/ui/Badge";
import { Pagination } from "../components/ui/Pagination";
import { label } from "../modules/product-research/format";
import { fetchReviewQueue,fetchReviewSettings,updateReviewSettings } from "../modules/supplier-policy-review/api";
import type { ReviewEvidenceType,ReviewItem,ReviewPage,ReviewSettings } from "../modules/supplier-policy-review/types";

const types:ReviewEvidenceType[]=["terms","robots","vat","shipping","official_api","buyma"];
const tone=(status:string)=>status==="up_to_date"?"success":status==="inconsistent"?"danger":"warning";

export function SupplierPolicyReviewPage(){
  const [sp,setSp]=useSearchParams();const [data,setData]=useState<ReviewPage|null>(null);const [settings,setSettings]=useState<ReviewSettings|null>(null);const [selected,setSelected]=useState<ReviewItem|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const [queue,nextSettings]=await Promise.all([fetchReviewQueue(sp.toString()),fetchReviewSettings()]);setData(queue);setSettings(nextSettings);setError("");}catch(e){setError(e instanceof Error?e.message:"Failed to load policy reviews.");}finally{setLoading(false);}},[sp]);
  useEffect(()=>{void load();},[load]);
  const change=(key:string,value:string)=>{const next=new URLSearchParams(sp);value?next.set(key,value):next.delete(key);if(key!=="page")next.set("page","1");setSp(next);};
  const save=async()=>{if(!settings)return;const {id:_,user_id:__,...body}=settings;void _;void __;try{setSettings(await updateReviewSettings(body));await load();}catch(e){setError(e instanceof Error?e.message:"Failed to save settings.");}};
  return <section className="page-section"><div className="page-section__header"><div><h1>Supplier Policy Review</h1><p>Review queue derived from current policy and immutable evidence. Policies are never changed automatically.</p></div></div>
    {error&&<div className="form-error-banner">{error}</div>}
    {data&&<div className="stats-grid" role="region" aria-label="Review summary">{[["Needs Review",data.total-data.summary.up_to_date],["Inconsistent",data.summary.inconsistent],["No Evidence",data.summary.no_evidence],["Up to Date",data.summary.up_to_date]].map(([name,value])=><article className="stat-card" key={String(name)}><strong>{name}</strong><div>{value}</div></article>)}</div>}
    <div className="panel research-toolbar" aria-label="Review filters"><select aria-label="Status" className="form-field__input" value={sp.get("overall_status")||""} onChange={e=>change("overall_status",e.target.value)}><option value="">All statuses</option>{["inconsistent","review_due","no_evidence","up_to_date"].map(x=><option value={x} key={x}>{label(x)}</option>)}</select><select aria-label="Evidence type" className="form-field__input" value={sp.get("evidence_type")||""} onChange={e=>change("evidence_type",e.target.value)}><option value="">All evidence types</option>{types.map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select aria-label="Country" className="form-field__input" value={sp.get("country")||""} onChange={e=>change("country",e.target.value)}><option value="">All countries</option>{["FR","DE","IT","ES","NL","BE","AT","IE","PT"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Supplier type" className="form-field__input" value={sp.get("supplier_type")||""} onChange={e=>change("supplier_type",e.target.value)}><option value="">All supplier types</option>{["authorized_retailer","department_store","boutique","marketplace","other","unknown"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><input aria-label="Brand" className="form-field__input" value={sp.get("brand")||""} onChange={e=>change("brand",e.target.value)} placeholder="Exact brand name"/><input aria-label="Keyword" className="form-field__input" value={sp.get("q")||""} onChange={e=>change("q",e.target.value)} placeholder="Supplier name"/></div>
    {loading?<div className="page-status">Loading policy reviews...</div>:!data?.items.length?<div className="panel panel--empty"><h2>No supplier policy reviews found.</h2></div>:<div className="panel"><div className="table-wrapper"><table className="data-table"><thead><tr><th>Supplier</th><th>Country</th><th>Brands</th><th>Review Status</th><th>Issue Type</th><th>Latest Evidence</th><th>Checked At / Age</th><th>Actions</th></tr></thead><tbody>{data.items.map(item=><tr key={item.supplier_id}><td>{item.supplier_name}</td><td>{item.country_code}</td><td>{item.brand_names.join(", ")||"-"}</td><td><Badge tone={tone(item.overall_status)}>{label(item.overall_status)}</Badge></td><td>{item.issue_types.map(label).join(", ")||"-"}</td><td>{item.issue_types[0]?label(item.types[item.issue_types[0]].latest_evidence||"No evidence"):"Up to date"}</td><td>{item.oldest_evidence_at?`${new Date(item.oldest_evidence_at).toLocaleDateString()} / ${Math.max(...Object.values(item.types).map(x=>x.age_days??0))} days`:"No evidence"}</td><td><button className="secondary-button" onClick={()=>setSelected(item)}>Review</button> <a className="text-link" href={`/suppliers?focus=${item.supplier_id}`}>Edit Supplier Policy</a></td></tr>)}</tbody></table></div><Pagination page={data} onPage={p=>change("page",String(p))} onPageSize={s=>change("page_size",String(s))}/></div>}
    {settings&&<section className="panel" aria-label="Review settings"><h2>Review Settings</h2><div className="form-grid">{types.map(type=><label className="form-field" key={type}>{label(type)} max age (days)<input className="form-field__input" type="number" min="1" max="3650" value={settings[`${type}_max_age_days` as keyof ReviewSettings] as number??""} onChange={e=>setSettings({...settings,[`${type}_max_age_days`]:e.target.value?Number(e.target.value):null})}/></label>)}</div><fieldset className="brand-picker"><legend>Required Evidence Types</legend>{types.map(type=><label className="checkbox-field" key={type}><input type="checkbox" checked={settings.required_evidence_types.includes(type)} onChange={e=>setSettings({...settings,required_evidence_types:e.target.checked?[...settings.required_evidence_types,type]:settings.required_evidence_types.filter(x=>x!==type)})}/>{label(type)}</label>)}</fieldset><button className="primary-button" onClick={()=>void save()}>Save Review Settings</button></section>}
    {selected&&<div className="modal-backdrop"><section className="modal-panel" aria-label="Supplier review detail"><div className="modal-panel__header"><h2>{selected.supplier_name}</h2><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button></div><p>Evidence alone does not complete a review when it conflicts with current policy.</p><table className="data-table"><thead><tr><th>Type</th><th>Current Policy</th><th>Latest Evidence</th><th>Consistency</th><th>Freshness</th><th>Status</th></tr></thead><tbody>{types.map(type=>{const x=selected.types[type];return <tr key={type}><td>{label(type)}</td><td>{label(x.current)}</td><td>{label(x.latest_evidence||"No evidence")}</td><td>{x.consistent===null?"No evidence":x.consistent?"Consistent":"Review required"}</td><td>{x.age_days===null?"-":`${x.age_days} / ${x.max_age_days??"disabled"} days`}</td><td>{label(x.review_status)}</td></tr>})}</tbody></table><a className="primary-button" href={`/suppliers?evidence=${selected.supplier_id}`}>Open Evidence History</a></section></div>}
  </section>;
}
